### ISSUE TITLE
- Error: Invalid coordinates. Must contain longitude and latitude

### ISSUE THREAD

**Issue by maantje** [brentschooley/pokespotter#3]
if (location.longitude && location.latitude) == false with the following location object
`{
    longitude : 0, 
    latitude : 0 
}` on line 124 in index.js. And will it will throw new Error('Invalid coordinates. Must contain longitude and latitude') even tough 0,0 are valid coordinates.

**Comment by dkundel** [comment]
Fair enough. That's poor checking on my side. I'll fix this and push a patch.

**Comment by dkundel** [comment]
Published a new version. Should be fixed in 0.1.3
