### ISSUE TITLE
API down ? find a solution ?

### ISSUE THREAD

**Issue by delmotte** [brentschooley/pokespotter#4]

**Comment by maantje** [comment]
The api was down for everyone and just go fixed [reddit](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/). So i am expecting it will work again soon.

**Comment by dkundel** [comment]
I'll be busy this week but try to incorporate the changes over the weekend. In the meantime updating the `pokemon-go-node-api` version should make it work again. This is basically just a wrapper.

**Comment by dkundel** [comment]
Alright I bumped the version and everything should be working again if you make sure that you have Pokespotter `0.1.5`.
